### PR TITLE
fix: admin_enqueue_scripts callback should expect a possible null value passed to it

### LINKED ISSUE #180: Can't move attendees in Events Calendar due to fatal errors caused by $hook_suffix type
### Description

This is a copy of the issue in WPGraphQL: https://github.com/wp-graphql/wp-graphql/issues/3056

Once the issue is fixed in WPGraphQL, the issue pops up in WPGraphQL for ACF as follows when trying to move attendees in Events Tickets Plus:
```Fatal error: Uncaught TypeError: Argument 1 passed to WPGraphQL\Acf\Admin\TaxonomyRegistration::enqueue_admin_scripts() must be of the type string, null given, called in /Users/craig/Local Sites/rmsv/app/public/wp-includes/class-wp-hook.php on line 324 and defined in /Users/craig/Local Sites/rmsv/app/public/wp-content/plugins/wpgraphql-acf/src/Admin/TaxonomyRegistration.php:174
```

### Steps to reproduce

1. Enable The Events Calendar, The Events Calendar Pro, Event Tickets and Event Tickets Plus.
2. Make a class with a ticket.
3. Sign up for the class.
4. Go to Attendees for that class.
5. Select an Attendee and use the Bulk action of "Move".

### PHP or JSON export of the ACF Field Group(s)

_No response_

### Additional context

In speaking with Jason, this can be fixed by changing the file mentioned above, plus https://github.com/wp-graphql/wpgraphql-acf/blob/develop/src/Admin/PostTypeRegistration.php#L169-L172 to use ?string $hook_suffix instead of string $hook_suffix.

### WPGraphQL Version

1.21.0

### WPGraphQL For ACF Version

2.1.2

### ACF (Advanced Custom Fields) Version. Free or Pro?

Pro

### WordPress Version

6.4.3

### PHP Version

7.4.30

### Additional enviornment details

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL, WPGraphQL For ACF, ACF, etc.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This updates the enqueue_admin_assets callback to expect a possible null value for the argument passed from `do_action( 'admin_enqueue_scripts' );`

Does this close any currently open issues?
------------------------------------------
closes #180

### CODE REVIEW

**Review by josephfusco — COMMENTED** [review]
I'm wondering if WP_Error could find it's way into one of these arguments. If so, maybe just removing the typed argument all together? 🤔

**Comment by jasonbahl** [comment]
@josephfusco ya, maybe 🤔 

That's the tricky thing with trying to adhere to code standards but also interacting with a filterable/hookable system like WordPress that doesn't always guarantee things will be what it says they will be 🤔

**Comment by jasonbahl** [comment]
@josephfusco that said, I'm inclined to think that whatever part of the system (likely a custom plugin or theme) is the culprit that's breaking the "contract" with what the value(s) should be.

WordPress documents that this value should be a string. If it's not a string, _something_ is causing it to not be a string and that _something_ should realistically be what's corrected 🤔

**Review by josephfusco — APPROVED** [review]
@jasonbahl Fair points! Looks good!

**Pull request merged**
